#!/usr/bin/env python3
"""
Student Project Hub — Lottie icon set.

These are generated by the SAME primitives, palette and timing curve as
scripts/build_lottie.py, so the student hub reads as part of the existing Gopang
icon system rather than a second visual language.

One local addition: `g()`. The shared group() only recognises a transform passed
via its `trs=` keyword, so a tag_tr() written inline as a shape-list item is left
behind inside `it` and never renders. g() accepts both forms and always hoists,
which keeps these icons readable without fighting the paren nesting.
"""

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import build_lottie as base

BLUE, CYAN, PURPLE, INK = base.BLUE, base.CYAN, base.PURPLE, base.INK
W = H = base.W
LOOP = base.LOOP

still, anim, loop_draw = base.still, base.anim, base.loop_draw
tr, tag_tr = base.tr, base.tag_tr
rect, ellipse, path = base.rect, base.ellipse, base.path
stroke, fill, trim = base.stroke, base.fill, base.trim
layer, ks_transform = base.layer, base.ks_transform


def g(items, name="grp"):
    """Like base.group but hoists any inline tag_tr() entries too."""
    hoisted = None
    keep = []
    for it in items:
        if isinstance(it, dict) and "__tr" in it:
            if hoisted is None:
                hoisted = it["__tr"]
        else:
            keep.append(it)
    return {"ty": "gr", "nm": name, "np": len(keep), "it": keep + [hoisted or tr()]}


# --------------------------------------------------------------- fragments ---
def check(size=30, color=CYAN, width=12):
    return g([
        path([[-size / 2, 0], [-size * 0.125, size * 0.31], [size / 2, -size * 0.34]]),
        trim(loop_draw(20, 54, LOOP - 54)),
        stroke(color, width),
    ], "check")


def dot(x, y, r, color, delay=0):
    return g([
        ellipse(r * 2, r * 2, 0, 0),
        fill(color),
        tag_tr(p=still([x, y]), o=anim([
            (delay, [0]), (delay + 14, [100]), (70, [100]), (82, [0]), (LOOP, [0]),
        ])),
    ], "dot")


def bar(x, y, w, h, color, opacity=80, delay=0, r=5):
    return g([
        rect(w, h, 0, 0, r),
        fill(color, opacity),
        tag_tr(p=still([x, y]), a=anim([
            (delay, [-w / 2, 0]), (delay + 18, [w / 2, 0]), (LOOP, [w / 2, 0]),
        ])),
    ], "bar")


def fade(delay=0, hold=70):
    return anim([(delay, [0]), (delay + 14, [100]), (hold, [100]), (hold + 12, [0]), (LOOP, [0])])


def pos3d(keys):
    """Layer positions must be 3-component vectors. A 2-component animated
    position is silently ignored by lottie-web, so the layer never moves."""
    out = []
    for i, (t, v) in enumerate(keys):
        val = list(v) + [0] if len(v) == 2 else list(v)
        if i < len(keys) - 1:
            out.append((t, val))
        else:
            out.append((t, val))
    return anim(out)


# ------------------------------------------------------------------- icons ---
def student_consultation():
    """A booked 30-minute slot on a calendar with a confirmation tick."""
    return [
        layer([
            g([
                rect(150, 158, 0, 0, 22),
                stroke(BLUE, 9),
                tag_tr(p=anim([(0, [0, 24]), (26, [0, 0]), (LOOP, [0, 0])])),
            ], "page"),
            g([
                rect(150, 40, 0, 0, 14),
                fill(BLUE, 85),
                tag_tr(p=still([0, -59])),
            ], "header"),
            g([
                rect(16, 28, 0, 0, 8),
                stroke(INK, 8),
                tag_tr(p=still([-50, -82])),
            ], "binderL"),
            g([
                rect(16, 28, 0, 0, 8),
                stroke(INK, 8),
                tag_tr(p=still([50, -82])),
            ], "binderR"),
            check(58, CYAN, 13),
        ], 1, "calendar"),
    ]


def student_mentor():
    """Consultant and student across a speech bubble — guidance."""
    return [
        layer([
            g([
                path([[-78, 6], [-78, -34], [0, -62], [78, -34], [78, 6], [78, 50], [0, 78], [-78, 50]], True),
                stroke(BLUE, 9),
            ], "bubble"),
            g([
                path([[-34, 66], [-34, 96], [4, 70]], False),
                fill(BLUE, 55),
            ], "tail"),
            dot(-30, -16, 9, BLUE),
            dot(30, -16, 9, CYAN, 10),
            g([
                path([[-22, 18], [0, 30], [22, 18]], False),
                stroke(PURPLE, 8),
                tag_tr(o=fade(20, 74)),
            ], "smile"),
        ], 1, "mentor"),
    ]


def student_journey():
    """Waypoints along a self-drawing route — the delivery journey."""
    pts = [(-96, 58), (-34, -20), (30, 24), (96, -58)]
    layers = [
        layer([
            g([
                path([[-96, 58], [-34, -20], [30, 24], [96, -58]], False),
                trim(loop_draw(50, 70, LOOP - 70)),
                stroke(BLUE, 8, 65),
            ], "route"),
        ], 1, "route"),
    ]
    for i, (x, y) in enumerate(pts):
        layers.append(layer([
            g([
                ellipse(32, 32, 0, 0),
                stroke(CYAN, 7),
                fill(BLUE, 20),
                tag_tr(s=anim([(i * 12, [40]), (i * 12 + 16, [112]), (LOOP, [112])])),
            ], "node"),
        ], 2 + i, "node%d" % i, ks=ks_transform(pos=still([x + 128, y + 128, 0]))))
    return layers


def student_delivery():
    """Package riding a conveyor toward a completion tick.

    Layer positions here are absolute artboard coordinates, so the parcel rides
    at y=142 to rest on the belt (belt line is y=128+50=178, box is 72 tall) and
    the tick lands just clear of the parcel lid at the far end of the run.
    """
    return [
        layer([
            g([
                rect(150, 9, 0, 0, 5),
                stroke(BLUE, 7, 50),
                tag_tr(p=still([0, 50])),
            ], "belt"),
            g([
                ellipse(16, 16, 0, 0),
                stroke(BLUE, 6, 55),
                tag_tr(p=still([-62, 50]), a=anim([(0, [0]), (48, [360]), (LOOP, [360])])),
            ], "wheelL"),
            g([
                ellipse(16, 16, 0, 0),
                stroke(BLUE, 6, 55),
                tag_tr(p=still([62, 50]), a=anim([(0, [0]), (48, [360]), (LOOP, [360])])),
            ], "wheelR"),
        ], 1, "conveyor"),
        layer([
            g([
                rect(86, 72, 0, 0, 10),
                stroke(CYAN, 9),
            ], "box"),
            g([
                path([[-43, -36], [43, -36]]),
                stroke(CYAN, 7),
            ], "lid"),
            g([
                path([[0, -36], [0, 36]]),
                stroke(CYAN, 6, 55),
            ], "tape"),
        ], 2, "parcel", ks=ks_transform(pos=pos3d([
            (0, [84, 142]), (32, [112, 142]), (60, [150, 142]),
            (74, [172, 142]), (LOOP, [84, 142]),
        ]))),
        layer([check(46, CYAN, 11)], 3, "ok",
              ks=ks_transform(pos=still([176, 70, 0]))),
    ]


def student_architecture():
    """Three modules wired to a shared spine — clean, maintainable structure."""
    # The spine is drawn around the group origin; its layer position already
    # places it at the centre, so it must NOT carry a second [128, 128] offset.
    layers = [
        layer([
            g([
                path([[0, -84], [0, 84]]),
                stroke(BLUE, 8, 55),
            ], "spine"),
        ], 1, "spine"),
    ]
    for i, (y, w, col) in enumerate([(-60, 108, PURPLE), (-12, 134, CYAN), (36, 100, BLUE)]):
        layers.append(layer([
            g([
                rect(w, 34, 0, 0, 10),
                stroke(col, 8),
                fill(col, 16),
            ], "module"),
            g([
                ellipse(13, 13, 0, 0),
                fill(col),
                tag_tr(p=still([-w / 2 - 16, 0]), o=anim([
                    (i * 10, [0]), (i * 10 + 16, [100]), (LOOP, [100]),
                ])),
            ], "core"),
        ], 2 + i, "layer%d" % i, ks=ks_transform(pos=still([128, 128 + y, 0]))))
    return layers


def student_deployment():
    """Cloud with a launch arrow rising out of it — shipping to production.

    The cloud is lifted to the top of the canvas and the arrow hangs below it so
    the two never collide while the arrow rises; together they stay inside the
    256x256 artboard (see scripts/check_lottie_bounds.py).
    """
    rise = anim([(0, [0, 14]), (30, [0, -10]), (LOOP, [0, 14])])
    return [
        layer([
            g([
                path([[-86, 28], [-62, -6], [-20, -10], [4, -46], [46, -40], [68, -6], [88, 8], [88, 40], [-86, 40]], True),
                stroke(BLUE, 9),
                tag_tr(p=still([0, -52])),
            ], "cloud"),
            g([
                path([[0, 34], [0, 80]]),
                trim(loop_draw(30, 58, LOOP - 58)),
                stroke(CYAN, 11),
                tag_tr(p=rise),
            ], "shaft"),
            g([
                path([[-24, 30], [0, 6], [24, 30]]),
                trim(loop_draw(30, 58, LOOP - 58)),
                stroke(CYAN, 11),
                tag_tr(p=rise),
            ], "head"),
        ], 1, "deploy"),
    ]


def student_documentation():
    """Document page with a heading, body lines and a bullet list."""
    return [
        layer([
            g([
                rect(140, 172, 0, 0, 14),
                stroke(BLUE, 9),
            ], "page"),
            bar(-4, -58, 96, 12, CYAN, 90, 6),
            bar(-12, -28, 112, 9, PURPLE, 60, 16),
            bar(-20, -8, 88, 9, PURPLE, 42, 26),
        ], 1, "doc"),
        layer([
            g([
                ellipse(11, 11, 0, 0),
                fill(CYAN),
                tag_tr(p=still([-44, 0]), o=anim([(0, [0]), (30, [100]), (56, [100]), (LOOP, [100])])),
            ], "b1"),
            bar(-2, 20, 84, 9, BLUE, 55, 0),
            g([
                ellipse(11, 11, 0, 0),
                fill(CYAN, 65),
                tag_tr(p=still([-48, 0]), o=anim([(0, [0]), (44, [100]), (68, [100]), (LOOP, [100])])),
            ], "b2"),
            bar(-8, 44, 64, 9, BLUE, 40, 14),
        ], 2, "bullets"),
    ]


def student_testing():
    """Flask with bubbling liquid, plus a passing assertion tick."""
    return [
        layer([
            g([
                path([[-38, -84], [-38, -18], [-74, 50], [-74, 76], [74, 76], [74, 50], [38, -18], [38, -84]], False),
                stroke(BLUE, 9),
            ], "flask"),
            g([
                rect(148, 9, 0, 0, 5),
                stroke(BLUE, 9),
                tag_tr(p=still([0, -84])),
            ], "rim"),
            g([
                path([[-64, 40], [-34, 2], [34, 2], [64, 40]]),
                fill(CYAN, 55),
                tag_tr(o=anim([(0, [100]), (44, [100]), (58, [0]), (LOOP, [0])])),
            ], "liquid"),
            g([
                ellipse(13, 13, 0, 0),
                fill(CYAN, 80),
                tag_tr(p=anim([(0, [-18, 66]), (36, [-18, -8]), (58, [-18, 66])])),
            ], "bubble1"),
            g([
                ellipse(10, 10, 0, 0),
                fill(BLUE, 70),
                tag_tr(p=anim([(0, [16, 60]), (48, [16, 0]), (68, [16, 60])])),
            ], "bubble2"),
        ], 1, "test"),
        layer([check(46, CYAN, 11)], 2, "ok", ks=ks_transform(pos=pos3d([
            (0, [128, 198]), (28, [128, 198]), (50, [128, 178]), (LOOP, [128, 178]),
        ]))),
    ]


def student_support():
    """Headset over a chat bubble — post-delivery assistance."""
    return [
        layer([
            g([
                path([[-76, 4], [-76, -28], [0, -66], [76, -28], [76, 4], [76, 48], [0, 74], [-76, 48]], True),
                stroke(BLUE, 9),
            ], "bubble"),
            g([
                path([[-30, 62], [-30, 90], [2, 66]], False),
                fill(BLUE, 55),
            ], "tail"),
            g([
                path([[-96, 14], [-96, -44], [96, -44], [96, 14]]),
                stroke(PURPLE, 10),
            ], "band"),
            g([
                rect(24, 44, 0, 0, 12),
                fill(PURPLE, 90),
                tag_tr(p=still([-94, -12])),
            ], "cupL"),
            g([
                rect(24, 44, 0, 0, 12),
                fill(PURPLE, 90),
                tag_tr(p=still([94, -12])),
            ], "cupR"),
            g([
                path([[96, 14], [96, 46], [58, 46]]),
                stroke(PURPLE, 8, 80),
            ], "mic"),
            g([
                ellipse(13, 13, 0, 0),
                fill(CYAN),
                tag_tr(p=still([46, 46]), o=anim([
                    (0, [0]), (20, [100]), (56, [100]), (72, [0]), (LOOP, [0]),
                ])),
            ], "tip"),
        ], 1, "support"),
    ]


def student_design():
    """Artboard with a moving design cursor and a snapping guide."""
    return [
        layer([
            g([
                rect(168, 152, 0, 0, 18),
                stroke(BLUE, 9),
                tag_tr(p=anim([(0, [0, 24]), (26, [0, 0]), (LOOP, [0, 0])])),
            ], "artboard"),
            g([
                rect(56, 56, -40, -30, 12),
                stroke(CYAN, 8),
            ], "box1"),
            g([
                rect(56, 24, 34, 30, 10),
                stroke(PURPLE, 8),
            ], "box2"),
            bar(-12, 50, 110, 10, BLUE, 70),
            bar(-22, 72, 84, 10, PURPLE, 45),
        ], 1, "canvas"),
        layer([
            g([
                path([[-20, -20], [4, 6], [28, -18]], False),
                fill(INK),
            ], "cursor"),
        ], 2, "cursor", ks=ks_transform(pos=pos3d([
            (0, [176, 172]), (30, [142, 200]), (58, [180, 178]), (LOOP, [176, 172]),
        ]))),
        layer([
            g([
                rect(5, 92, 0, 0, 2),
                stroke(CYAN, 4, 65),
                # Sweeps inside the artboard outline (x 39.5-216.5, y 47.5-208.5).
                tag_tr(p=anim([(0, [20, 20]), (26, [76, 20]), (LOOP, [20, 20])])),
            ], "guideH"),
        ], 3, "guides"),
    ]


def student_code():
    """Editor window with a code line and a blinking caret."""
    return [
        layer([
            g([
                rect(188, 152, 0, 0, 20),
                stroke(BLUE, 9),
                tag_tr(p=anim([(0, [0, 26]), (26, [0, 0]), (LOOP, [0, 0])])),
            ], "window"),
            g([
                rect(172, 30, 0, 0, 8),
                fill(BLUE, 65),
                tag_tr(p=still([0, -60])),
            ], "titlebar"),
            dot(70, 12, 5, CYAN),
            dot(88, 12, 5, PURPLE),
        ], 1, "editor"),
        layer([
            g([
                rect(34, 12, 0, 0, 5),
                fill(PURPLE, 85),
                tag_tr(p=still([-62, 0]), s=anim([
                    (0, [0, 100]), (22, [0, 100]), (26, [100, 100]), (LOOP, [100, 100]),
                ])),
            ], "kw"),
            g([
                rect(60, 12, 0, 0, 5),
                fill(CYAN, 85),
                tag_tr(p=still([-16, 0]), s=anim([
                    (0, [0, 100]), (34, [0, 100]), (38, [100, 100]), (LOOP, [100, 100]),
                ])),
            ], "fn"),
            g([
                rect(20, 12, 0, 0, 5),
                fill(BLUE, 70),
                tag_tr(p=still([22, 0]), s=anim([
                    (0, [0, 100]), (46, [0, 100]), (50, [100, 100]), (LOOP, [100, 100]),
                ])),
            ], "op"),
            bar(-54, 30, 70, 9, BLUE, 42, 54),
            bar(-20, 30, 52, 9, PURPLE, 38, 62),
            bar(-56, 58, 40, 9, CYAN, 38, 70),
        ], 2, "code"),
        layer([
            g([
                rect(4, 24, 0, 0, 2),
                fill(INK, 90),
                tag_tr(o=anim([(0, [0]), (22, [0]), (25, [100]), (48, [100]), (51, [0]), (LOOP, [0])])),
            ], "caret"),
        ], 3, "caret", ks=ks_transform(pos=still([158, 176, 0]))),
    ]


ICONS = {
    "student-consultation": student_consultation,
    "student-mentor": student_mentor,
    "student-journey": student_journey,
    "student-delivery": student_delivery,
    "student-architecture": student_architecture,
    "student-deployment": student_deployment,
    "student-documentation": student_documentation,
    "student-testing": student_testing,
    "student-support": student_support,
    "student-design": student_design,
    "student-code": student_code,
}


def build(name):
    layers = ICONS[name]()
    layers.sort(key=lambda l: l["ind"])
    for i, l in enumerate(layers):
        l["ind"] = i + 1
        # Icons are drawn around the origin and the layer places them on the
        # 256x256 canvas. Without this the whole composition sits in the top-left
        # corner and most of it is cropped out of the mount.
        p = l["ks"]["p"]
        if p.get("a") != 1 and p.get("k") == [0, 0, 0]:
            p["k"] = [W / 2, H / 2, 0]
    return {
        "v": "5.7.4", "fr": base.FR, "ip": 0, "op": LOOP,
        "w": W, "h": H, "nm": "gis-" + name, "ddd": 0,
        "assets": [], "layers": layers, "markers": [],
    }


def main():
    out = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "assets", "lottie"
    )
    os.makedirs(out, exist_ok=True)
    total = 0
    for name in sorted(ICONS):
        data = build(name)
        path = os.path.join(out, name + ".json")
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, separators=(",", ":"))
        size = os.path.getsize(path)
        total += size
        print("%-26s %2d layers  %5d B" % (name, len(data["layers"]), size))
    print("-" * 46)
    print("%d icons, %.1f KB total" % (len(ICONS), total / 1024.0))


if __name__ == "__main__":
    main()