#!/usr/bin/env python3
"""Add an in-depth original section to each service page.

The 11 service pages each sat at roughly 880-980 words, and most of that was
marketing scaffolding shared between them: a six-step process strip, a row of
technology chips, an industries grid. Little of it was specific to the service,
which is thin from a reader's point of view and near-duplicate from a crawler's.

This script injects a long, genuinely service-specific section — technical
decisions, what goes wrong in that discipline, what you receive — immediately
before the FAQ block on each page. Content lives one file per service in
``scripts/service-src/<slug>.html``; nothing is shared between them, so the
pages do not read as one template with the nouns swapped.

Each partial is split into the main column and the sidebar by an ``<!--ASIDE-->``
marker.

Idempotent: the injected block is fenced by a marker comment, and re-running
replaces the block rather than stacking another copy.

Run from the repo root:  python scripts/expand_services.py
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = Path(__file__).resolve().parent / "service-src"

BEGIN = "<!-- BEGIN service-deep-dive (generated by scripts/expand_services.py) -->"
END = "<!-- END service-deep-dive -->"

FAQ_ANCHOR = '    <section class="svc-section faq-wrapper">'
BLOG_CSS = '    <link rel="stylesheet" href="/assets/css/pages/blog.css?v=1">'
SVC_CSS_RE = re.compile(r'(    <link rel="stylesheet" href="/assets/css/pages/service-detail\.css[^"]*">\n)')

# slug -> (eyebrow, heading, intro paragraph shown above the prose)
PAGES = {
    "mobile-app-development": (
        "In Depth",
        "What actually goes into shipping a mobile app",
        "Most of the cost and nearly all of the risk in a mobile project sits outside the screens people imagine. Here is the part of the work that is invisible in a design file.",
    ),
    "web-development": (
        "In Depth",
        "The decisions that shape a web project",
        "Four or five choices made in the first week determine what the site costs to run, who can update it, and how it behaves in two years. These are the ones worth understanding.",
    ),
    "ui-ux-design": (
        "In Depth",
        "Design that survives contact with engineering",
        "Attractive screens are the easy part. What separates a design that ships from one that gets quietly redrawn in code is everything below.",
    ),
    "custom-software-development": (
        "In Depth",
        "Where custom systems succeed or quietly fail",
        "Custom business software is not priced by screens. It is priced by roles, rules and reporting — and it fails on data, not on code.",
    ),
    "ecommerce-development": (
        "In Depth",
        "The parts of an online store nobody demos",
        "Storefronts sell well in a pitch. Orders, stock, payments and returns are where an e-commerce build is actually won or lost.",
    ),
    "backend-api-development": (
        "In Depth",
        "What separates an API you can build on from one you rewrite",
        "A backend is a contract other software depends on. These are the decisions that are cheap now and very expensive to reverse later.",
    ),
    "cloud-devops": (
        "In Depth",
        "The infrastructure work that stops 2am phone calls",
        "DevOps is not a tool you install. It is a set of boring guarantees: you can deploy safely, you can see what broke, and you can get your data back.",
    ),
    "ai-machine-learning": (
        "In Depth",
        "How we build AI features that hold up in production",
        "Demos are easy and misleading. Everything below exists because a probabilistic system behaves differently once real data and real users reach it.",
    ),
    "quality-assurance-testing": (
        "In Depth",
        "What real testing looks like, and what it costs",
        "Testing is not a phase at the end of a Gantt chart. It is a set of habits, a device matrix and an agreed definition of what counts as broken.",
    ),
    "maintenance-support": (
        "In Depth",
        "What a maintenance retainer actually buys",
        "Software does not sit still after launch. Here is the work that keeps a system alive, and how we scope and price it honestly.",
    ),
    "it-consulting": (
        "In Depth",
        "When consulting is worth paying for — and when it is not",
        "Advice is easy to sell and hard to value. So here is exactly what we produce, what it is for, and the cases where you should not hire us.",
    ),
}


def build_block(slug: str) -> str:
    eyebrow, heading, intro = PAGES[slug]
    raw = (SRC / f"{slug}.html").read_text(encoding="utf-8").strip()
    if "<!--ASIDE-->" not in raw:
        raise SystemExit(f"{slug}.html is missing the <!--ASIDE--> marker")
    main, aside = (part.strip() for part in raw.split("<!--ASIDE-->", 1))

    return f"""{BEGIN}
    <section class="svc-section" id="in-depth" style="border-top:1px solid var(--gis-border);">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <span style="display:inline-block;color:var(--gis-accent);font-weight:700;font-size:.78rem;letter-spacing:.14em;text-transform:uppercase;margin-bottom:12px;">{eyebrow}</span>
                    <h2 style="font-size:clamp(1.6rem,3vw,2.1rem);margin-bottom:16px;">{heading}</h2>
                    <p style="font-size:1.08rem;color:var(--gis-ink);margin-bottom:8px;">{intro}</p>
                    <div class="gis-prose">
{main}
                    </div>
                </div>
                <div class="col-lg-4">
                    <div style="position:sticky;top:24px;">
{aside}
                    </div>
                </div>
            </div>
        </div>
    </section>
{END}
"""


def process(slug: str) -> str:
    path = ROOT / slug / "index.html"
    html = path.read_text(encoding="utf-8")
    original = html
    block = build_block(slug)

    # blog.css carries .gis-prose / .gis-callout / .gis-table-scroll
    if "pages/blog.css" not in html:
        html, n = SVC_CSS_RE.subn(lambda m: m.group(1) + BLOG_CSS + "\n", html, count=1)
        if not n:
            raise SystemExit(f"{slug}: could not find the service-detail.css link to anchor blog.css to")

    if BEGIN in html:
        # replace the existing generated block
        html = re.sub(
            re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?",
            block,
            html,
            flags=re.DOTALL,
        )
        action = "regenerated"
    else:
        if FAQ_ANCHOR not in html:
            raise SystemExit(f"{slug}: FAQ anchor not found")
        html = html.replace(FAQ_ANCHOR, block + FAQ_ANCHOR, 1)
        action = "inserted"

    if html == original:
        return f"unchanged   {slug}"
    path.write_text(html, encoding="utf-8")

    words = len(re.sub(r"<[^>]+>", " ", block).split())
    return f"{action:<11} {slug}  (+{words} words)"


def main() -> None:
    total = 0
    for slug in PAGES:
        result = process(slug)
        print(result)
        m = re.search(r"\+(\d+) words", result)
        if m:
            total += int(m.group(1))
    print(f"\n{total} words of new service-specific copy across {len(PAGES)} pages")


if __name__ == "__main__":
    main()
