#!/usr/bin/env python3
"""Sitewide premium upgrade: inject the experience assets and navigation.

What it does, per public page (idempotent — running twice changes nothing):

  1. Adds the Google Fonts <link> (Plus Jakarta Sans + Space Grotesk) when the
     page does not already request it.
  2. Appends /assets/css/gis-experience.css as the LAST stylesheet so the
     experience layer wins every cascade tie.
  3. Appends /assets/js/gis-experience.js after premium.js (or before </body>).
  4. Swaps the dark logo artwork for the light variants generated by
     scripts/make_light_logo.py (header SVG, footer PNG).
  5. Upgrades the navigation to the enterprise IA:
       Home · Services · Work · Industries · Insights · Company · Apply · Contact
     and relabels the nav CTA to "Start a Project".

Skips: scripts/ (templates), admin source trees are still processed for assets
but never for navigation (they have no gis-main-menu), plus .git/node_modules.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SKIP_PARTS = {"scripts", ".git", "node_modules", ".freebuff"}

FONT_LINK = (
    '    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?'
    "family=Plus+Jakarta+Sans:wght@400;500;600;700;800&"
    'family=Space+Grotesk:wght@500;600;700&display=swap">'
)
CSS_LINK = '    <link rel="stylesheet" href="/assets/css/gis-experience.css?v=1">'
JS_TAG = '    <script src="/assets/js/gis-experience.js?v=1" defer></script>'

LINK_RE = re.compile(r'[ \t]*<link rel="stylesheet"[^>]*>')
PREMIUM_JS_RE = re.compile(r'[ \t]*<script src="/assets/js/premium\.js[^"]*"[^>]*></script>')
BODY_CLOSE_RE = re.compile(r'[ \t]*</body>')


def html_files():
    for path in sorted(ROOT.rglob("*.html")):
        rel = path.relative_to(ROOT)
        if any(part in SKIP_PARTS for part in rel.parts):
            continue
        yield path


def inject_assets(text):
    """Returns (new_text, notes)."""
    notes = []

    if "fonts.googleapis.com/css2" not in text and LINK_RE.search(text):
        m = LINK_RE.search(text)
        text = text[: m.start()] + FONT_LINK + "\n" + text[m.start():]
        notes.append("fonts")

    if "gis-experience.css" not in text:
        matches = list(LINK_RE.finditer(text))
        if matches:
            last = matches[-1]
            end = last.end()
            text = text[:end] + "\n" + CSS_LINK + text[end:]
            notes.append("css")

    if "gis-experience.js" not in text:
        js = PREMIUM_JS_RE.search(text)
        if js:
            end = js.end()
            text = text[:end] + "\n" + JS_TAG + text[end:]
            notes.append("js")
        else:
            body = BODY_CLOSE_RE.search(text)
            if body:
                text = text[: body.start()] + JS_TAG + "\n" + text[body.start():]
                notes.append("js")

    before = text
    text = text.replace('src="/assets/img/logo.svg"', 'src="/assets/img/logo-light.svg"')
    text = text.replace('src="/assets/img/logo-footer.png"', 'src="/assets/img/logo-light.png"')
    if text != before:
        notes.append("logo")

    return text, notes


def upgrade_nav(text):
    notes = []
    if "gis-main-menu" not in text or ">Work</a>" not in text:
        return text, notes

    # 1. Industries, right before Insights (desktop + mobile menu)
    if 'href="/#industries"' not in text:
        def add_industries(m):
            indent = m.group(1)
            return f'{indent}<li><a href="/#industries">Industries</a></li>\n{indent}{m.group(2)}'

        text, n = re.subn(
            r'([ \t]*)(<li><a href="/blog">Insights</a></li>)',
            add_industries,
            text,
        )
        if n:
            notes.append(f"industries-{n}")

    # 2. Contact goes right after the Apply block (desktop + mobile menu).
    #    Only touch Contact lines when the Apply block exists so we can always
    #    put one back — otherwise we would lose the item on nav variants.
    apply_re = re.compile(r'[ \t]*<li><a href="#">Apply.*?</ul>\s*</li>', re.S)
    if apply_re.search(text):
        text, n = re.subn(r'[ \t]*<li><a href="/contact">Contact</a></li>\n?', '', text)
        if n:
            notes.append(f"drop-contact-{n}")

        text, n = re.subn(
            r'([ \t]*)(<li><a href="#">Apply.*?</ul>\s*</li>)',
            lambda m: m.group(0) + f'\n{m.group(1)}<li><a href="/contact">Contact</a></li>',
            text,
            flags=re.S,
        )
        if n:
            notes.append(f"contact-{n}")

    # 3. nav CTA wording
    text, n1 = re.subn(
        r'(<a href="/contact" class="theme-btn theme-btn-sm gis-nav-cta[^"]*"[^>]*>)Let\'s Talk ',
        r'\1Start a Project ',
        text,
    )
    text, n2 = re.subn(
        r'(<a href="/contact" class="gis-mobile-cta">)Let\'s Talk →',
        r'\1Start a Project →',
        text,
    )
    if n1 or n2:
        notes.append(f"cta-{n1 + n2}")

    return text, notes


def main():
    changed = 0
    for path in html_files():
        original = path.read_text(encoding="utf-8")
        text = original

        text, asset_notes = inject_assets(text)
        text, nav_notes = upgrade_nav(text)

        if text != original:
            path.write_text(text, encoding="utf-8")
            changed += 1
            rel = path.relative_to(ROOT)
            print(f"{rel}: {', '.join(asset_notes + nav_notes)}")

    print(f"\n{changed} file(s) updated")


if __name__ == "__main__":
    main()
